schema:
  - ${NEXT_PUBLIC_CONTENT_GRAPH_ENDPOINT} 
documents:
  - "./graphql/**/*.graphql"
generates:
  ./generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo